[package]
name = "chttp"
version = "0.1.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]

[features]
default = ["json"]

[dependencies]
curl = "0.4"
http = "0.1.1"

[dependencies.json]
version = "0.11"
optional = true
