[package]
name = "chttp"
version = "0.5.0-alpha.1"
description = "The practical HTTP client that is fun to use."
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
license = "MIT"
keywords = ["http", "request", "client"]
categories = ["web-programming::http-client"]
repository = "https://github.com/sagebind/chttp"
documentation = "https://docs.rs/chttp/"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges.maintenance]
status = "actively-developed"

[features]
default = ["cookies", "http2", "static-curl"]
cookies = ["chrono"]
http2 = ["curl/http2"]
nightly = []
psl = ["parking_lot", "publicsuffix"]
static-curl = ["curl/static-curl"]
middleware-api = []

[dependencies]
bytes = "0.4"
crossbeam-channel = "0.3"
curl = "^0.4.20"
curl-sys = "^0.4.20"
futures-preview = "=0.3.0-alpha.17"
http = "0.1"
lazy_static = "1"
log = "0.4"
slab = "0.4"
sluice = "0.4.0-alpha.2"

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.parking_lot]
version = "0.8"
optional = true

[dependencies.publicsuffix]
version = "1.5"
default-features = false
optional = true

[dev-dependencies]
env_logger = "0.6"
rayon = "1"
rouille = "3"

[[example]]
name = "async"
required-features = ["nightly"]

[workspace]
members = ["benchmarks"]
