[package]
name = "chttp"
version = "0.5.0-alpha.1"
description = "The practical HTTP client that is fun to use."
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
license = "MIT"
keywords = ["http", "request", "client"]
categories = ["web-programming::http-client"]
repository = "https://github.com/sagebind/chttp"
documentation = "https://docs.rs/chttp/"
readme = "README.md"
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[badges.maintenance]
status = "actively-developed"

[features]
default = ["cookies", "http2", "static-curl"]
cookies = ["chrono"]
http2 = ["curl/http2"]
nightly = []
static-curl = ["curl/static-curl"]
middleware-api = []

[dependencies]
auto_enums = "0.5"
bytes = "0.4"
crossbeam-channel = "0.3"
curl = "^0.4.20"
curl-sys = "^0.4.20"
futures-preview = "=0.3.0-alpha.17"
http = "0.1"
lazy_static = "1"
log = "0.4"
regex = "1.1"
slab = "0.4"
sluice = "0.4.0-alpha.2"
static_assertions = "0.3"

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.psl]
version = "0.4"
optional = true

[dev-dependencies]
criterion = "0.2"
env_logger = "0.6"
rayon = "1"
reqwest = "0.9"
rouille = "3"

[[bench]]
name = "download"
harness = false

[[example]]
name = "async"
required-features = ["nightly"]
