[package]
name = "chttp"
version = "0.4.4"
description = "The practical HTTP client that is fun to use."
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
license = "MIT"
keywords = ["http", "request", "client"]
categories = ["web-programming::http-client"]
repository = "https://github.com/sagebind/chttp"
documentation = "https://docs.rs/chttp/"
readme = "README.md"
edition = "2018"

[badges.maintenance]
status = "actively-developed"

[features]
default = ["cookies", "http2", "static-curl"]
cookies = ["chrono"]
http2 = ["curl/http2"]
static-curl = ["curl/static-curl"]
middleware-api = []

[dependencies]
bytes = "0.4"
# crossbeam = "0.7"
curl = "^0.4.20"
http = "0.1"
lazy_static = "1"
lazycell = "1.2"
log = "0.4"
regex = "1.1"
slab = "0.4"
sluice = "0.4.0-alpha.1"
static_assertions = "0.3"
withers_derive = "0.2"

[dependencies.futures-preview]
version = "0.3.0-alpha.16"

[dependencies.chrono]
version = "0.4"
optional = true

[dependencies.json]
version = "0.11"
optional = true

[dependencies.psl]
version = "0.4"
optional = true

[dev-dependencies]
criterion = "0.2"
rayon = "1"

[dev-dependencies.utilities]
path = "utilities"

[package.metadata.docs.rs]
all-features = true

[[bench]]
name = "download"
harness = false

[[example]]
name = "async"
required-features = ["async-api"]

[workspace]
members = ["utilities"]
