name: ci
on: push

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        features:
          - ""
          - "mesalink"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - name: Install Rust (macOS)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain 1.36.0
        if: runner.os == 'macOS'

      - run: rustup default 1.36.0
        shell: "bash -l {0}"

      - run: cargo test --features 'psl ${{ matrix.features }}' -- --test-threads=8
        shell: "bash -l {0}"
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: isahc=debug

      - run: cargo run --features 'psl ${{ matrix.features }}' --release --example simple
        shell: "bash -l {0}"
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: isahc=debug

  test-nightly:
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - run: cargo test --features psl,nightly -- --test-threads=8
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: isahc=debug
