name: ci
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "1.36.0"
          default: true

      - run: cargo test --features psl -- --test-threads=8
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: isahc=debug

      - run: cargo run --release --example simple
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: isahc=debug

  test-nightly:
    runs-on: ubuntu-latest
    container: rustlang/rust:nightly
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true

      - run: cargo test --features psl,nightly -- --test-threads=8
        env:
          RUST_BACKTRACE: 1
          RUST_LOG: isahc=debug
