name: configure repo
on:
  push:
    branches: [master]

jobs:
  configure-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: micnncim/action-label-syncer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
