name: release
on: release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        if: github.event.action == 'published'
        with:
          submodules: true

      - name: Publish to crates.io
        if: github.event.action == 'published'
        run: |
          cargo login "${CARGO_TOKEN}"
          cargo publish
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
